### ISSUE TITLE
[FEATURE] Création de la page de suivi des progrès

### ISSUE THREAD

**Issue by Pinappll** [Pinappll/Gestionnaire-Auto-Ecole-en-PHP#24]
# FEATURE REQUEST

### Description de la Fonctionnalité
Permet de suivre la progression individuelle des élèves. Elle permet aux gestionnaires et moniteurs d'avoir une vue des compétences acquises, des leçons terminées, et des évaluations passées par chaque élève.

#### User story 

En tant que gestionnaire d'auto-école,

Je souhaite disposer d'un outil de suivi des progrès des élèves,

Afin de personnaliser l'enseignement, d'adapter les plans de formation en fonction des besoins spécifiques de chaque élève, et d'optimiser l'efficacité de l'auto-école,

Dans le but de garantir une expérience d'apprentissage individualisée, de maximiser le taux de réussite aux évaluations, et d'améliorer la satisfaction des élèves.

### Contenu supplémentaires
- Profil de progression individuel pour chaque élève, affichant les leçons terminées, les compétences acquises, les évaluations, etc.
- Outils pour les instructeurs et les gestionnaires pour mettre à jour et suivre les progrès des élèves.

**Comment by ludovicMAK** [comment]
Ma solution est de créer un dashboard pour un élève
